[package]
name = "sol-contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.16.10"
borsh = "1.3.1"
borsh-derive = "1.3.1"

[lib]
crate-type = ["cdylib", "lib"]
